### ISSUE TITLE
Re-integrate prisma-multi-tenant in mrapi

### ISSUE THREAD

**Issue by Errorname** [mrapi-js/mrapi#4]
It looks like you copied part of the code of [`prisma-multi-tenant`](https://github.com/Errorname/prisma-multi-tenant) in your @mrapi/multi-tenant package. (See https://github.com/mrapi-js/mrapi/search?q=prisma-multi-tenant&unscoped_q=prisma-multi-tenant)

Since `prisma-multi-tenant` is actively maintained, you could miss a lot of great features and bugfixes by not using it.

If there is some issues or improvement on `prisma-multi-tenant`, I'd love to hear them too :)

**Comment by 364734461** [comment]
Good. We've already used PMT in the new version.
