### ISSUE TITLE
error: the current connector does not support enums

### ISSUE THREAD

**Issue by kiragame** [mrapi-js/mrapi#40]
## Bug description 问题描述
when executing "npm run dev", there's an error occurred during generating code.
```code
error: Error validating: You defined the enum `XEnum`. But the current connector does not support enums.
```

## How to reproduce 如何复现
my prisma schema:
```code
model Test {
    xStatus XEnum @default(ONE)
}

enum XEnum {
  ONE
  TWO
  THREE
}
...
```
-->

## Expected behavior 预期行为
Generate successfully. And no error occurs.

## Environment & setup 环境设置

- OS: 
- Database: MySQL
- Node.js version: v12.18.3
- Mrapi versions
  - `@mrapi/cli`: "^1.0.0-beta.4"
  - `@mrapi/api`: "^1.0.0-beta.4"
  - `@mrapi/dal`: "^1.0.0-beta.4"
- Prisma versions
  - `@prisma/cli`: "^2.4.1"
  - `@prisma/client`: "^^2.4.1"

## Screenshots 截图

![image](https://user-images.githubusercontent.com/20295007/93420531-b4086300-f8e1-11ea-87f0-f0dfea9f68e3.png)

**Comment by kiragame** [comment]
Relate issue:  https://github.com/prisma/prisma/issues/3449

That's the question sqlite doesn't support enums but mrapi generating schema is ```code  provider = ["sqlite", "mysql", "postgresql"]  ```

**Comment by 364734461** [comment]
这是个问题，周末前会完成修复！
